from pathlib import Path
root=Path('/mnt/data/MR-VISUALCRAFT-NEW2/public')

def header(active=''):
    links=[('Work','/work'),('Services','/services'),('Process','/process'),('About','/about'),('Contact','/contact')]
    return f'''<header class="nav"><div class="wrap navin"><a class="brand" href="/"><span class="logo">M</span><span>MR VISUALCRAFT<small>IDEAS · DESIGN · DIGITAL · AI</small></span></a><nav class="links">{''.join(f'<a class="{("active" if active==href else "")}" href="{href}">{name}</a>' for name,href in links)}</nav><div class="navActions"><a class="btn" href="/cv">CV ↗</a><a class="btn primary" href="/contact">Start a project ↗</a><button class="hamb" aria-label="Open menu">☰</button></div></div></header>'''

def footer():
    return '''<footer class="footer"><div class="wrap footerIn"><div>© 2026 MR VISUALCRAFT · Ubaidullah</div><div><a href="mailto:mrvisualcraft@gmail.com">mrvisualcraft@gmail.com</a> · <a target="_blank" href="https://www.instagram.com/ubaidullah141/">Instagram</a> · <a target="_blank" href="https://www.tiktok.com/@ubaidullah141">TikTok</a> · <a target="_blank" href="https://www.behance.net/ubaidullah141">Behance</a></div></div></footer><script src="/app.js" defer></script>'''

def page(title,body,active=''):
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="MR VISUALCRAFT — Ubaidullah. Web, brand, AI and digital marketing."><title>{title} — MR VISUALCRAFT</title><link rel="stylesheet" href="/style.css"></head><body>{header(active)}<main>{body}</main>{footer()}</body></html>'''

services=[('Web Development','cyan','Build','Premium websites, landing pages and web apps with strong UX and responsive implementation.','/services/web'),('Graphic & Brand Design','violet','✦','Identity systems, campaign graphics, social kits and visual direction.','/services/design'),('AI & Agentic Systems','lime','AI','Assistants, automations and internal tools around real business tasks.','/services/ai'),('Digital Marketing','orange','↗','Content systems, social campaigns and conversion-focused creative.','/services/marketing')]
projects=[('NovaTech','WEB','browser','Corporate product website and conversion system.','/work/nova'),('UrbanBrand','BRAND','brandVisual','Identity and social design system.','/work/urban'),('SmartAgent','AI','aiVisual','AI assistant and automation workflow.','/work/smart'),('GrowthX','GROWTH','marketingVisual','Campaign and content performance system.','/work/growth'),('ContentFlow','CONTENT','contentVisual','Editorial content engine and visual system.','/work/content'),('LaunchKit','CAMPAIGN','campaignVisual','Launch campaign creative direction.','/work/brand')]

hero='''<section class="hero"><div class="wrap heroGrid"><div class="reveal"><div class="eyebrow"><span class="dot"></span> Independent creative studio · Available for selected work</div><h1>Ideas that <span class="accent">look sharp.</span><br>Digital that <span class="accent2">moves.</span></h1><p class="lead">I’m Ubaidullah — the designer and developer behind MR VISUALCRAFT. I build polished websites, visual systems, AI workflows and digital campaigns that feel considered from the first click.</p><div class="actions"><a class="btn primary" href="/work">Explore work ↗</a><a class="btn" href="/contact">Let’s talk ↗</a></div><div class="meta"><span>WEB</span><span>BRAND</span><span>AI</span><span>GROWTH</span></div></div><div class="heroVisual reveal"><div class="orb"></div><div class="stroke"></div><img class="person" src="/assets/portrait.png" alt="Ubaidullah"><div class="float f1"><b>Visual systems</b><span>Brand · UI · content</span></div><div class="float f2"><b>AI + automation</b><span>Useful workflows</span></div><div class="signature">Ubaidullah</div><div class="mail">mrvisualcraft@gmail.com<br>@ubaidullah141<br>Instagram · TikTok · Behance</div></div></div></section><div class="marquee"><div class="wrap"><span>DESIGN SYSTEMS</span><span>WEB EXPERIENCES</span><span>AI WORKFLOWS</span><span>DIGITAL CAMPAIGNS</span><span>VISUAL STORYTELLING</span></div></div>'''
svc_html=''.join(f'<a class="card" href="{u}"><div class="icon {c}">{ic}</div><h3>{n}</h3><p>{d}</p><span class="arrow">Open service →</span></a>' for n,c,ic,d,u in services)
work_html=''.join(f'<a class="card workCard" href="{u}"><div class="visual {vis}">{"<div class=browser><div class=bar></div><div class=bars><div></div><div></div><div></div><div></div></div></div>" if vis=="browser" else ""}</div><div class="workBody"><span class="tag">{tag}</span><h3>{n}</h3><p>{d}</p><span class="arrow">Open case study →</span></div></a>' for n,tag,vis,d,u in projects)
body=hero+f'''<section class="section"><div class="wrap"><div class="sectionHead"><div><div class="kicker">Services</div><h2>Four disciplines. One system.</h2></div><a class="btn" href="/services">View all →</a></div><div class="grid4">{svc_html}</div></div></section><section class="section"><div class="wrap"><div class="sectionHead"><div><div class="kicker">Selected work</div><h2>Built to be clicked, used and remembered.</h2></div><a class="btn" href="/work">View all work →</a></div><div class="workGrid">{work_html}</div></div></section><section class="section"><div class="wrap split"><div class="panel"><div class="kicker">About</div><h2>Design, development, AI and growth — connected.</h2><p class="sub">MR VISUALCRAFT is my independent creative practice. I combine visual thinking with practical building so a project does not stop at a pretty screen.</p><div class="stats"><div class="stat"><strong>4</strong><span>Core disciplines</span></div><div class="stat"><strong>20+</strong><span>Builds & concepts</span></div><div class="stat"><strong>1</strong><span>Creative system</span></div></div><br><a class="btn" href="/about">Read about me →</a></div><div class="panel portraitPanel"><img src="/assets/portrait.png" alt="Ubaidullah"></div></div></section><section class="section"><div class="wrap"><div class="sectionHead"><div><div class="kicker">Process</div><h2>From rough idea to finished launch.</h2></div><a class="btn" href="/process">See process →</a></div><div class="steps"><div class="step"><span class="num">01</span><h3>Discover</h3><p>Goals, audience, constraints and direction.</p></div><div class="step"><span class="num">02</span><h3>Shape</h3><p>Structure, content and visual language.</p></div><div class="step"><span class="num">03</span><h3>Build</h3><p>Responsive implementation and interaction.</p></div><div class="step"><span class="num">04</span><h3>Launch</h3><p>QA, polish, handoff and support.</p></div></div></div></section><section class="section"><div class="wrap"><div class="panel" style="display:flex;justify-content:space-between;align-items:center;gap:25px"><div><div class="kicker">Let’s work together</div><h2>Have something worth building?</h2><p class="sub">Tell me what you are trying to make. I’ll turn the brief into a clear next step.</p></div><a class="btn primary" href="/contact">Start a project →</a></div></div></section>'''
(root/'index.html').write_text(page('Ubaidullah',body))

# work page
workbody=f'''<section class="pageHero"><div class="wrap"><div class="kicker">Selected work</div><h1>Projects with a <span class="accent">point of view.</span></h1><p class="lead">Concept case studies across web, brand, AI and growth. Each project opens into a full detail page.</p></div></section><section class="section"><div class="wrap"><div class="workGrid">{work_html}</div></div></section>'''
(root/'work.html').write_text(page('Work',workbody,'/work'))
# services page
(root/'services.html').write_text(page('Services',f'''<section class="pageHero"><div class="wrap"><div class="kicker">Services</div><h1>Build the <span class="accent">right thing.</span></h1><p class="lead">Choose a discipline or combine them into one coherent digital launch.</p></div></section><section class="section"><div class="wrap"><div class="grid4">{svc_html}</div></div></section>''','/services'))
# process/about/contact/cv/admin
(root/'process.html').write_text(page('Process','''<section class="pageHero"><div class="wrap"><div class="kicker">Process</div><h1>A clear path from <span class="accent">idea to impact.</span></h1><p class="lead">Simple stages, visible decisions and a polished handoff.</p></div></section><section class="section"><div class="wrap"><div class="steps"><div class="step"><span class="num">01</span><h3>Discover</h3><p>Brief, goals, audience, references and constraints.</p></div><div class="step"><span class="num">02</span><h3>Direction</h3><p>Structure, content hierarchy and visual route.</p></div><div class="step"><span class="num">03</span><h3>Build</h3><p>Responsive UI, motion, interactions and backend where needed.</p></div><div class="step"><span class="num">04</span><h3>Refine</h3><p>QA, performance polish, launch and support.</p></div></div></div></section>''','/process'))
(root/'about.html').write_text(page('About','''<section class="pageHero"><div class="wrap"><div class="kicker">About</div><h1>Ubaidullah / <span class="accent">MR VISUALCRAFT.</span></h1><p class="lead">A creative practice built around design, development, AI and digital growth.</p></div></section><section class="section"><div class="wrap split"><div class="panel portraitPanel"><img src="/assets/portrait.png" alt="Ubaidullah"></div><div class="panel"><div class="kicker">My approach</div><h2>Make it clear. Make it useful. Make it memorable.</h2><p class="sub">I like visual systems that have a reason behind them and digital products that feel obvious to use. I move between design and implementation so ideas stay connected all the way through.</p><div class="stats"><div class="stat"><strong>WEB</strong><span>Interfaces & builds</span></div><div class="stat"><strong>BRAND</strong><span>Visual systems</span></div><div class="stat"><strong>AI</strong><span>Automation & agents</span></div></div></div></div></section>''','/about'))
(root/'contact.html').write_text(page('Contact','''<section class="pageHero"><div class="wrap"><div class="kicker">Contact</div><h1>Let’s make the <span class="accent">next move.</span></h1><p class="lead">Tell me what you are building, what you need and when you want to move.</p></div></section><section class="section"><div class="wrap split"><div class="panel"><div class="kicker">Direct</div><h2>mrvisualcraft@gmail.com</h2><p class="sub">Instagram · @ubaidullah141<br>TikTok · @ubaidullah141<br>Behance · ubaidullah141</p><a class="btn primary" href="mailto:mrvisualcraft@gmail.com">Email me →</a></div><div class="panel"><form class="form" id="contactForm"><input name="name" placeholder="Your name" required><input name="email" type="email" placeholder="Email address" required><input name="project" placeholder="What are you building?" required><textarea name="message" placeholder="Tell me a little about it…" required></textarea><button class="btn primary" type="submit">Send message →</button><div class="status" id="formStatus"></div></form></div></div></section>''','/contact'))
(root/'cv.html').write_text(page('CV','''<section class="pageHero"><div class="wrap"><div class="kicker">CV</div><h1>Ubaidullah — <span class="accent">Creative Designer & Developer.</span></h1><p class="lead">Web development · Graphic & brand design · AI & agentic systems · Digital marketing</p><div class="actions"><a class="btn primary" href="mailto:mrvisualcraft@gmail.com?subject=CV%20Request">Request CV ↗</a><a class="btn" href="/contact">Contact me →</a></div></div></section><section class="section"><div class="wrap split"><div class="panel"><div class="kicker">Capabilities</div><ul class="list"><li>Responsive web design & development</li><li>Brand identity and social creative systems</li><li>AI assistants and workflow automation</li><li>Content strategy and digital campaigns</li></ul></div><div class="panel"><div class="kicker">Tools & mindset</div><p class="sub">Design systems · UI/UX · HTML/CSS/JS · Node.js · AI workflows · content systems · campaign creative</p><a class="btn" href="/work">See selected work →</a></div></div></section>''',''))
(root/'admin.html').write_text(page('Admin','''<section class="pageHero"><div class="wrap"><div class="kicker">Admin</div><h1>Message <span class="accent">inbox.</span></h1><p class="lead">Local backend submissions appear here.</p></div></section><section class="section"><div class="wrap" id="adminList"><div class="panel">Loading…</div></div></section>''',''))

# project/service detail pages
proj_data={
'nova':('NovaTech','WEB','A conversion-focused corporate website system.','browser','Information architecture, responsive UI, reusable sections and a clearer conversion path.'),
'urban':('UrbanBrand','BRAND','A modern identity and social content system.','brandVisual','Logo direction, typography, social templates, campaign language and rollout structure.'),
'smart':('SmartAgent','AI','An AI assistant concept for repeatable operations.','aiVisual','Conversation design, workflow mapping, tool actions and a human-friendly control surface.'),
'growth':('GrowthX','GROWTH','A content and campaign system built for consistent publishing.','marketingVisual','Content pillars, campaign creative, landing-page direction and reporting-ready structure.'),
'content':('ContentFlow','CONTENT','An editorial system for turning ideas into repeatable content.','contentVisual','Content architecture, visual templates, publishing workflow and reusable creative rules.'),
'brand':('LaunchKit','CAMPAIGN','A launch campaign system designed to feel coherent across channels.','campaignVisual','Campaign concept, social creative, landing direction, CTA hierarchy and rollout plan.')}
for slug,(name,tag,desc,vis,details) in proj_data.items():
    visual=f'<div class="visual {vis} detailVisual">'+('<div class="browser"><div class="bar"></div><div class="bars"><div></div><div></div><div></div><div></div></div></div>' if vis=='browser' else '')+'</div>'
    body=f'''<section class="pageHero"><div class="wrap"><a class="btn" href="/work">← All work</a><div class="kicker" style="margin-top:28px">{tag}</div><h1>{name} — <span class="accent">case study.</span></h1><p class="lead">{desc}</p></div></section><section class="section"><div class="wrap detailGrid"><div>{visual}</div><div class="panel"><div class="kicker">What was built</div><h2>{details}</h2><p class="sub">This is a concept case study demonstrating how the project could be structured, designed and delivered.</p><ul class="list"><li>Clear information architecture</li><li>Responsive visual system</li><li>Interaction and content direction</li><li>Launch-ready handoff structure</li></ul><a class="btn primary" href="/contact">Discuss a similar project →</a></div></div></section>'''
    (root/f'project_{slug}.html').write_text(page(name,body,'/work'))
svc_data={'web':('Web Development','cyan','Websites that feel premium and work hard.','Web experiences, landing pages and useful applications with responsive UI, clear structure and polished interaction.'),'design':('Graphic & Brand Design','violet','Visual systems people can recognize.','Brand identity, social systems, campaign graphics, UI direction and reusable creative templates.'),'ai':('AI & Agentic Systems','lime','Automation built around real tasks.','Assistants, workflows and agentic systems designed to reduce repetitive work and make information easier to act on.'),'marketing':('Digital Marketing','orange','Creative that supports growth.','Content systems, social creative, campaign direction, landing pages and conversion-focused messaging.')}
for slug,(name,col,headline,desc) in svc_data.items():
    body=f'''<section class="pageHero"><div class="wrap"><a class="btn" href="/services">← All services</a><div class="kicker" style="margin-top:28px">Service</div><h1>{headline}</h1><p class="lead">{desc}</p></div></section><section class="section"><div class="wrap split"><div class="panel"><div class="icon {col}">✦</div><h2>What you get</h2><ul class="list"><li>Clear scope and project direction</li><li>High-quality visual and content system</li><li>Responsive implementation where relevant</li><li>QA, refinement and launch support</li></ul><a class="btn primary" href="/contact">Start a project →</a></div><div class="panel"><div class="kicker">Typical flow</div><h2>Brief → direction → build → refine.</h2><p class="sub">The process stays visible so you know what is being solved and what happens next.</p><div class="steps"><div class="step"><span class="num">01</span><h3>Brief</h3><p>Goals and constraints.</p></div><div class="step"><span class="num">02</span><h3>Direction</h3><p>Visual and content route.</p></div><div class="step"><span class="num">03</span><h3>Build</h3><p>Execution and interaction.</p></div><div class="step"><span class="num">04</span><h3>Refine</h3><p>QA and launch.</p></div></div></div></div></section>'''
    (root/f'service_{slug}.html').write_text(page(name,body,'/services'))
