const http=require('http'),fs=require('fs'),path=require('path'),url=require('url'),zlib=require('zlib');
const root=path.join(__dirname,'public'), data=path.join(__dirname,'data','messages.json');
if(!fs.existsSync(path.dirname(data))) fs.mkdirSync(path.dirname(data),{recursive:true});
if(!fs.existsSync(data)) fs.writeFileSync(data,'[]');
const routes={'/':'index.html','/work':'work.html','/services':'services.html','/process':'process.html','/about':'about.html','/contact':'contact.html','/cv':'cv.html','/admin':'admin.html','/work/nova':'project_nova.html','/work/urban':'project_urban.html','/work/smart':'project_smart.html','/work/growth':'project_growth.html','/work/content':'project_content.html','/work/brand':'project_brand.html','/services/web':'service_web.html','/services/design':'service_design.html','/services/ai':'service_ai.html','/services/marketing':'service_marketing.html'};
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.ico':'image/x-icon'};
function requireAdmin(req,res){const expectedUser='ubaid',expectedPassword='03378914810',header=req.headers.authorization||'';const unauthorized=(msg)=>{res.writeHead(401,{'Content-Type':'text/plain; charset=utf-8','WWW-Authenticate':'Basic realm="MR VISUALCRAFT Admin"','Cache-Control':'no-store'});res.end(msg);return false};if(!header.startsWith('Basic '))return unauthorized('Admin login required.');try{const decoded=Buffer.from(header.slice(6),'base64').toString('utf8'),separator=decoded.indexOf(':');if(separator===-1)return unauthorized('Invalid login.');if(decoded.slice(0,separator)!==expectedUser||decoded.slice(separator+1)!==expectedPassword)return unauthorized('Invalid login.');return true}catch(e){return unauthorized('Invalid login.')}}
function send(res,status,body,type='text/plain; charset=utf-8',cache='no-store'){const raw=Buffer.isBuffer(body)?body:Buffer.from(String(body));const canGzip=/^(text\/|application\/(javascript|json))/.test(type)&&raw.length>512;const headers={'Content-Type':type,'Cache-Control':cache,'Vary':'Accept-Encoding'};if(canGzip&&/gzip/.test(''+res.req.headers['accept-encoding'])){headers['Content-Encoding']='gzip';zlib.gzip(raw,(e,b)=>{if(e){res.writeHead(status,headers);return res.end(raw)}res.writeHead(status,{...headers,'Content-Length':b.length});res.end(b)});return}res.writeHead(status,{...headers,'Content-Length':raw.length});res.end(raw)}
function staticFile(res,p){if(p.includes('..'))return send(res,403,'Forbidden');const f=path.join(root,p);if(!fs.existsSync(f)||!fs.statSync(f).isFile())return send(res,404,'Not found');const ext=path.extname(f).toLowerCase(),type=mime[ext]||'application/octet-stream',cache=ext==='.html'?'no-cache':'public, max-age=86400';send(res,200,fs.readFileSync(f),type,cache)}
const server=http.createServer((req,res)=>{const u=url.parse(req.url,true);if(req.method==='GET'&&u.pathname==='/api/health')return send(res,200,JSON.stringify({ok:true,service:'MR VISUALCRAFT'}),'application/json');if(req.method==='GET'&&u.pathname==='/api/messages'){if(!requireAdmin(req,res))return;return send(res,200,fs.readFileSync(data),'application/json')}if(req.method==='POST'&&u.pathname==='/api/contact'){let b='';req.on('data',c=>b+=c);req.on('end',()=>{try{const x=JSON.parse(b||'{}');if(!x.name||!x.email||!x.message)return send(res,400,JSON.stringify({ok:false,error:'Name, email and message are required.'}),'application/json');x.phone=[x.phoneCountry||'',String(x.phone||'').trim()].filter(Boolean).join(' ').trim();delete x.phoneCountry;const arr=JSON.parse(fs.readFileSync(data));arr.unshift({...x,id:Date.now(),createdAt:new Date().toISOString()});fs.writeFileSync(data,JSON.stringify(arr,null,2));send(res,200,JSON.stringify({ok:true}),'application/json')}catch(e){send(res,400,JSON.stringify({ok:false,error:'Invalid request'}),'application/json')}});return}if(req.method==='GET'){if(u.pathname==='/admin'){if(!requireAdmin(req,res))return}if(routes[u.pathname])return staticFile(res,routes[u.pathname]);if(u.pathname.endsWith('.html'))return staticFile(res,u.pathname.slice(1));if(u.pathname.startsWith('/assets/'))return staticFile(res,u.pathname.slice(1));if(u.pathname==='/style.css'||u.pathname==='/app.js')return staticFile(res,u.pathname.slice(1));if(u.pathname==='/favicon.ico')return send(res,404,'')}send(res,404,'Page not found')});
server.listen(process.env.PORT||3000,()=>console.log(`MR VISUALCRAFT running on http://localhost:${process.env.PORT||3000}`));
